language: clojure
lein: lein2

addons:
  postgresql: "9.3"

before_script:
  - createdb -e -U postgres -E UTF-8 -O $USER tamarack
  - sudo apt-get install phantomjs npm
  - sudo npm config set registry http://registry.npmjs.org/
  - sudo npm install -g karma
  - sudo npm install -g karma-phantomjs-launcher
  - sudo npm install -g karma-jasmine

script:
  - lein cljsbuild once
  - lein midje
  - /usr/local/lib/node_modules/karma/bin/karma start --single-run
